// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app-components': string;
  'background': string;
  'loading': string;
}
export const cssExports: CssExports;
export default cssExports;
