// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'completed': string;
  'new-todo-button-div': string;
  'new-todo-form-div': string;
  'pastDue': string;
  'todo-caption': string;
  'todo-children': string;
  'todo-description': string;
  'todo-div': string;
}
export const cssExports: CssExports;
export default cssExports;
