// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'topbar-button': string;
  'topbar-children': string;
  'topbar-div': string;
}
export const cssExports: CssExports;
export default cssExports;
